VERSION 0.7
FROM golang:1.17-alpine
WORKDIR /go-workdir

build:
    COPY go.mod go.sum main.go .
    COPY greetings greetings
    RUN go build -o output/example main.go
    SAVE ARTIFACT output/example AS LOCAL local-output/go-example
